[hosts]
  [hosts.test]
    user = "teste"
    host = "192.168.1.1"
    port = 22
    desc = "lab"
    tags = ["lab"]
[hosts.umbrel]
user = "umbrel"
host = "192.168.18.238"
port = 22
desc = "Lab"
tags = ["lab"]

